import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { MainNav } from "@/components/main-nav";
import Footer from "@/components/footer";

const font = DM_Sans({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "rybnikonline.eu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={font.className}>
      <body className={`antialiased bg-slate-900 overflow-x-hidden font-sans`}>
        <MainNav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
